name: Synchronize Paper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force:
        default: false
        description: Force build all Paper images
        type: boolean

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write

jobs:
  synchronize:
    secrets: inherit
    uses: $/.github/workflows/synchronize.yml
    with:
      force: ${{ inputs.force || false }}
      project: paper
